/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's github repository.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VidGenPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  provider: "luma",
  lumaApiKey: "",
  runwayApiKey: "",
  defaultAspectRatio: "16:9",
  defaultDuration: "5s",
  defaultResolution: "720p",
  saveVideosTo: "VidGen",
  historyLimit: 20
};

// src/SettingsTab.ts
var import_obsidian = require("obsidian");
var VidGenSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("vidgen-settings");
    containerEl.createEl("h2", { text: "VidGen Settings" });
    containerEl.createEl("p", {
      text: "Configure your AI video generation provider and defaults.",
      cls: "vidgen-settings-desc"
    });
    containerEl.createEl("h3", { text: "Provider" });
    new import_obsidian.Setting(containerEl).setName("Video Provider").setDesc("Choose which AI service to use for video generation.").addDropdown(
      (drop) => drop.addOption("luma", "Luma AI (Ray-2)").addOption("runway", "Runway ML (Gen-4 Turbo)").setValue(this.plugin.settings.provider).onChange(async (value) => {
        this.plugin.settings.provider = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "API Keys" });
    new import_obsidian.Setting(containerEl).setName("Luma AI API Key").setDesc(
      createFragment((frag) => {
        frag.appendText("Your Luma AI API key. Get one at ");
        frag.createEl("a", {
          text: "lumalabs.ai",
          attr: { href: "https://lumalabs.ai/dream-machine/api/keys", target: "_blank" }
        });
        frag.appendText(".");
      })
    ).addText(
      (text) => text.setPlaceholder("luma-...").setValue(this.plugin.settings.lumaApiKey).onChange(async (value) => {
        this.plugin.settings.lumaApiKey = value.trim();
        await this.plugin.saveSettings();
      })
    ).addButton(
      (btn) => btn.setButtonText("Test").setCta().onClick(async () => {
        await this.testLumaKey();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Runway ML API Key").setDesc(
      createFragment((frag) => {
        frag.appendText("Your Runway ML API key. Get one at ");
        frag.createEl("a", {
          text: "runwayml.com",
          attr: { href: "https://app.runwayml.com/settings/api-keys", target: "_blank" }
        });
        frag.appendText(".");
      })
    ).addText(
      (text) => text.setPlaceholder("key_...").setValue(this.plugin.settings.runwayApiKey).onChange(async (value) => {
        this.plugin.settings.runwayApiKey = value.trim();
        await this.plugin.saveSettings();
      })
    ).addButton(
      (btn) => btn.setButtonText("Test").setCta().onClick(async () => {
        await this.testRunwayKey();
      })
    );
    containerEl.createEl("h3", { text: "Defaults" });
    new import_obsidian.Setting(containerEl).setName("Default Aspect Ratio").setDesc("The aspect ratio used when opening the generator.").addDropdown(
      (drop) => drop.addOption("16:9", "16:9 \u2013 Landscape").addOption("9:16", "9:16 \u2013 Portrait").addOption("1:1", "1:1 \u2013 Square").addOption("4:3", "4:3 \u2013 Classic").addOption("3:4", "3:4 \u2013 Tall Classic").setValue(this.plugin.settings.defaultAspectRatio).onChange(async (value) => {
        this.plugin.settings.defaultAspectRatio = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default Duration").setDesc("Default video length.").addDropdown(
      (drop) => drop.addOption("5s", "5 seconds").addOption("10s", "10 seconds").setValue(this.plugin.settings.defaultDuration).onChange(async (value) => {
        this.plugin.settings.defaultDuration = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default Resolution").setDesc("Default output resolution.").addDropdown(
      (drop) => drop.addOption("540p", "540p \u2013 Fast").addOption("720p", "720p \u2013 Balanced").addOption("1080p", "1080p \u2013 High Quality").setValue(this.plugin.settings.defaultResolution).onChange(async (value) => {
        this.plugin.settings.defaultResolution = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("History Limit").setDesc("Maximum number of generations to keep in history.").addSlider(
      (slider) => slider.setLimits(5, 50, 5).setValue(this.plugin.settings.historyLimit).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.historyLimit = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "About" });
    const about = containerEl.createDiv({ cls: "vidgen-about" });
    about.createEl("p", {
      text: "VidGen uses Luma AI or Runway ML to generate short videos from text descriptions. Videos are generated in the cloud and streamed back to Obsidian."
    });
  }
  async testLumaKey() {
    const key = this.plugin.settings.lumaApiKey;
    if (!key) {
      new import_obsidian.Notice("Please enter a Luma AI API key first.");
      return;
    }
    new import_obsidian.Notice("Testing Luma AI key...");
    try {
      const resp = await fetch("https://api.lumalabs.ai/dream-machine/v1/generations?limit=1", {
        headers: { Authorization: `Bearer ${key}`, Accept: "application/json" }
      });
      if (resp.ok) {
        new import_obsidian.Notice("Luma AI key is valid!");
      } else {
        new import_obsidian.Notice(`Luma AI key test failed: ${resp.status} ${resp.statusText}`);
      }
    } catch (e) {
      new import_obsidian.Notice(`Luma AI key test error: ${e}`);
    }
  }
  async testRunwayKey() {
    const key = this.plugin.settings.runwayApiKey;
    if (!key) {
      new import_obsidian.Notice("Please enter a Runway ML API key first.");
      return;
    }
    new import_obsidian.Notice("Testing Runway ML key...");
    try {
      const resp = await fetch("https://api.runwayml.com/v1/tasks?limit=1", {
        headers: {
          Authorization: `Bearer ${key}`,
          "X-Runway-Version": "2024-11-06"
        }
      });
      if (resp.ok) {
        new import_obsidian.Notice("Runway ML key is valid!");
      } else {
        new import_obsidian.Notice(`Runway ML key test failed: ${resp.status} ${resp.statusText}`);
      }
    } catch (e) {
      new import_obsidian.Notice(`Runway ML key test error: ${e}`);
    }
  }
};

// src/VideoGeneratorView.ts
var import_obsidian2 = require("obsidian");

// src/providers/LumaProvider.ts
var LUMA_API_BASE = "https://api.lumalabs.ai/dream-machine/v1";
var LumaProvider = class {
  constructor(apiKey) {
    this.apiKey = apiKey;
    this.name = "Luma AI";
  }
  async startGeneration(request) {
    const body = {
      prompt: request.prompt,
      model: "ray-2",
      resolution: request.resolution,
      duration: request.duration,
      aspect_ratio: request.aspectRatio
    };
    const response = await fetch(`${LUMA_API_BASE}/generations`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.apiKey}`,
        Accept: "application/json"
      },
      body: JSON.stringify(body)
    });
    if (!response.ok) {
      const err = await response.json().catch(() => ({ detail: response.statusText }));
      throw new Error(`Luma API error ${response.status}: ${err.detail || JSON.stringify(err)}`);
    }
    const data = await response.json();
    return data.id;
  }
  async pollStatus(id) {
    var _a, _b, _c;
    const response = await fetch(`${LUMA_API_BASE}/generations/${id}`, {
      headers: {
        Authorization: `Bearer ${this.apiKey}`,
        Accept: "application/json"
      }
    });
    if (!response.ok) {
      throw new Error(`Poll failed: ${response.statusText}`);
    }
    const data = await response.json();
    const statusMap = {
      queued: "queued",
      dreaming: "dreaming",
      processing: "processing",
      completed: "completed",
      failed: "failed"
    };
    const status = (_a = statusMap[data.state]) != null ? _a : "processing";
    return {
      status,
      videoUrl: (_b = data.assets) == null ? void 0 : _b.video,
      thumbnailUrl: (_c = data.assets) == null ? void 0 : _c.image,
      completedAt: data.completed_at ? new Date(data.completed_at).getTime() : void 0,
      error: data.failure_reason
    };
  }
};

// src/providers/RunwayProvider.ts
var RUNWAY_API_BASE = "https://api.runwayml.com/v1";
var RunwayProvider = class {
  constructor(apiKey) {
    this.apiKey = apiKey;
    this.name = "Runway ML";
  }
  async startGeneration(request) {
    const durationSec = parseInt(request.duration.replace("s", ""), 10);
    const body = {
      model: "gen4_turbo",
      promptText: request.prompt,
      ratio: request.aspectRatio,
      duration: durationSec
    };
    const response = await fetch(`${RUNWAY_API_BASE}/text_to_video`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.apiKey}`,
        "X-Runway-Version": "2024-11-06"
      },
      body: JSON.stringify(body)
    });
    if (!response.ok) {
      const err = await response.json().catch(() => ({ error: response.statusText }));
      throw new Error(`Runway API error ${response.status}: ${err.error || JSON.stringify(err)}`);
    }
    const data = await response.json();
    return data.id;
  }
  async pollStatus(id) {
    var _a;
    const response = await fetch(`${RUNWAY_API_BASE}/tasks/${id}`, {
      headers: {
        Authorization: `Bearer ${this.apiKey}`,
        "X-Runway-Version": "2024-11-06"
      }
    });
    if (!response.ok) {
      throw new Error(`Poll failed: ${response.statusText}`);
    }
    const data = await response.json();
    const statusMap = {
      PENDING: "queued",
      RUNNING: "processing",
      SUCCEEDED: "completed",
      FAILED: "failed",
      CANCELLED: "failed"
    };
    const status = (_a = statusMap[data.status]) != null ? _a : "processing";
    const videoUrl = data.output && data.output.length > 0 ? data.output[0] : void 0;
    return {
      status,
      videoUrl,
      completedAt: status === "completed" ? Date.now() : void 0,
      error: data.failure
    };
  }
};

// src/VideoGeneratorView.ts
var VIEW_TYPE_VIDGEN = "vidgen-view";
var EXAMPLE_PROMPTS = [
  "A cinematic aerial shot of a misty mountain range at sunrise",
  "A cozy coffee shop in the rain, people walking by with umbrellas",
  "An astronaut floating through a colorful nebula in space",
  "A time-lapse of a blooming flower in a sunlit garden",
  "Ocean waves crashing on a rocky shore at golden hour",
  "A futuristic city skyline at night with neon lights reflecting on wet streets"
];
var ASPECT_RATIOS = [
  { value: "16:9", label: "Landscape", icon: "monitor" },
  { value: "9:16", label: "Portrait", icon: "smartphone" },
  { value: "1:1", label: "Square", icon: "square" }
];
var VideoGeneratorView = class extends import_obsidian2.ItemView {
  constructor(leaf, settings, history, onSaveHistory) {
    super(leaf);
    this.history = [];
    this.isGenerating = false;
    this.settings = settings;
    this.history = history;
    this.onSaveHistory = onSaveHistory;
    this.aspectRatioEl = settings.defaultAspectRatio;
    this.durationEl = settings.defaultDuration;
    this.resolutionEl = settings.defaultResolution;
  }
  getViewType() {
    return VIEW_TYPE_VIDGEN;
  }
  getDisplayText() {
    return "VidGen";
  }
  getIcon() {
    return "video";
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  async onOpen() {
    this.renderUI();
  }
  async onClose() {
  }
  renderUI() {
    const root = this.contentEl;
    root.empty();
    root.addClass("vidgen-root");
    const header = root.createDiv({ cls: "vidgen-header" });
    header.createEl("h2", { text: "VidGen", cls: "vidgen-title" });
    const subtitle = header.createEl("p", { cls: "vidgen-subtitle" });
    subtitle.setText("AI Video Generator");
    const content = root.createDiv({ cls: "vidgen-content" });
    this.renderPromptSection(content);
    this.renderOptionsSection(content);
    this.renderGenerateButton(content);
    this.statusSection = content.createDiv({ cls: "vidgen-status-section vidgen-hidden" });
    this.outputSection = content.createDiv({ cls: "vidgen-output-section vidgen-hidden" });
    this.historySection = content.createDiv({ cls: "vidgen-history-section" });
    this.renderHistory();
  }
  renderPromptSection(parent) {
    const section = parent.createDiv({ cls: "vidgen-section" });
    const labelRow = section.createDiv({ cls: "vidgen-label-row" });
    labelRow.createEl("label", { text: "Prompt", cls: "vidgen-label" });
    const randomBtn = labelRow.createEl("button", {
      cls: "vidgen-random-btn",
      title: "Get a random example prompt"
    });
    (0, import_obsidian2.setIcon)(randomBtn, "shuffle");
    randomBtn.createSpan({ text: " Inspire me" });
    randomBtn.addEventListener("click", () => {
      const example = EXAMPLE_PROMPTS[Math.floor(Math.random() * EXAMPLE_PROMPTS.length)];
      this.promptEl.value = example;
      this.promptEl.dispatchEvent(new Event("input"));
      this.promptEl.focus();
    });
    this.promptEl = section.createEl("textarea", {
      cls: "vidgen-prompt-input",
      attr: {
        placeholder: "Describe the video you want to create...\n\nTip: Be specific about lighting, camera movement, mood, and setting.",
        rows: "5"
      }
    });
    const charCount = section.createDiv({ cls: "vidgen-char-count" });
    charCount.setText("0 / 500");
    this.promptEl.addEventListener("input", () => {
      const len = this.promptEl.value.length;
      charCount.setText(`${len} / 500`);
      charCount.toggleClass("vidgen-char-warn", len > 400);
      charCount.toggleClass("vidgen-char-over", len > 500);
    });
  }
  renderOptionsSection(parent) {
    const section = parent.createDiv({ cls: "vidgen-section" });
    section.createEl("p", { text: "Options", cls: "vidgen-label" });
    const arGroup = section.createDiv({ cls: "vidgen-option-group" });
    arGroup.createEl("span", { text: "Aspect Ratio", cls: "vidgen-option-label" });
    const arButtons = arGroup.createDiv({ cls: "vidgen-ratio-buttons" });
    ASPECT_RATIOS.forEach(({ value, label, icon }) => {
      const btn = arButtons.createEl("button", {
        cls: `vidgen-ratio-btn ${value === this.aspectRatioEl ? "active" : ""}`,
        title: label
      });
      (0, import_obsidian2.setIcon)(btn, icon);
      btn.createSpan({ text: ` ${value}` });
      btn.addEventListener("click", () => {
        this.aspectRatioEl = value;
        arButtons.querySelectorAll(".vidgen-ratio-btn").forEach(
          (b) => b.removeClass("active")
        );
        btn.addClass("active");
      });
    });
    const row = section.createDiv({ cls: "vidgen-option-row" });
    const durGroup = row.createDiv({ cls: "vidgen-option-group" });
    durGroup.createEl("span", { text: "Duration", cls: "vidgen-option-label" });
    const durSelect = durGroup.createEl("select", { cls: "vidgen-select" });
    ["5s", "10s"].forEach((d) => {
      const opt = durSelect.createEl("option", { value: d, text: d });
      if (d === this.durationEl)
        opt.selected = true;
    });
    durSelect.addEventListener("change", () => {
      this.durationEl = durSelect.value;
    });
    const resGroup = row.createDiv({ cls: "vidgen-option-group" });
    resGroup.createEl("span", { text: "Resolution", cls: "vidgen-option-label" });
    const resSelect = resGroup.createEl("select", { cls: "vidgen-select" });
    ["540p", "720p", "1080p"].forEach((r) => {
      const opt = resSelect.createEl("option", { value: r, text: r });
      if (r === this.resolutionEl)
        opt.selected = true;
    });
    resSelect.addEventListener("change", () => {
      this.resolutionEl = resSelect.value;
    });
    const providerRow = section.createDiv({ cls: "vidgen-provider-row" });
    providerRow.createEl("span", { text: "Provider:", cls: "vidgen-option-label" });
    const providerBadge = providerRow.createEl("span", {
      cls: "vidgen-provider-badge",
      text: this.settings.provider === "luma" ? "Luma AI" : "Runway ML"
    });
    providerBadge.setAttribute("data-provider", this.settings.provider);
  }
  renderGenerateButton(parent) {
    const wrapper = parent.createDiv({ cls: "vidgen-generate-wrapper" });
    this.generateBtn = wrapper.createEl("button", {
      cls: "vidgen-generate-btn",
      text: "Generate Video"
    });
    (0, import_obsidian2.setIcon)(this.generateBtn, "sparkles");
    this.generateBtn.addEventListener("click", () => {
      this.handleGenerate();
    });
  }
  async handleGenerate() {
    if (this.isGenerating)
      return;
    const prompt = this.promptEl.value.trim();
    if (!prompt) {
      new import_obsidian2.Notice("Please enter a prompt first.");
      this.promptEl.focus();
      return;
    }
    if (prompt.length > 500) {
      new import_obsidian2.Notice("Prompt is too long. Please keep it under 500 characters.");
      return;
    }
    const apiKey = this.settings.provider === "luma" ? this.settings.lumaApiKey : this.settings.runwayApiKey;
    if (!apiKey) {
      new import_obsidian2.Notice(
        `No API key set. Go to Settings > VidGen to add your ${this.settings.provider === "luma" ? "Luma AI" : "Runway ML"} API key.`
      );
      return;
    }
    const request = {
      prompt,
      aspectRatio: this.aspectRatioEl,
      duration: this.durationEl,
      resolution: this.resolutionEl,
      provider: this.settings.provider
    };
    await this.startGeneration(request);
  }
  async startGeneration(request) {
    this.isGenerating = true;
    this.generateBtn.disabled = true;
    this.generateBtn.setText("Generating...");
    this.statusSection.removeClass("vidgen-hidden");
    this.outputSection.addClass("vidgen-hidden");
    this.renderStatus("queued", "Sending request...");
    const record = {
      id: `gen-${Date.now()}`,
      internalId: "",
      prompt: request.prompt,
      provider: request.provider,
      aspectRatio: request.aspectRatio,
      duration: request.duration,
      status: "queued",
      createdAt: Date.now()
    };
    try {
      const provider = this.getProvider();
      const internalId = await provider.startGeneration(request);
      record.internalId = internalId;
      this.renderStatus("processing", "Video is being generated...");
      await this.pollUntilDone(provider, record);
    } catch (err) {
      record.status = "failed";
      record.error = String(err);
      this.renderStatus("failed", `Generation failed: ${record.error}`);
      new import_obsidian2.Notice(`VidGen: ${record.error}`);
    } finally {
      this.isGenerating = false;
      this.generateBtn.disabled = false;
      this.generateBtn.setText("Generate Video");
      this.addToHistory(record);
    }
  }
  async pollUntilDone(provider, record) {
    var _a;
    const maxAttempts = 120;
    let attempts = 0;
    const pollInterval = 5e3;
    while (attempts < maxAttempts) {
      await sleep(pollInterval);
      attempts++;
      try {
        const update = await provider.pollStatus(record.internalId);
        Object.assign(record, update);
        const statusMessages = {
          queued: "Queued, waiting to start...",
          dreaming: "Dreaming up your video...",
          processing: `Processing... (${attempts * 5}s elapsed)`,
          completed: "Done!",
          failed: `Failed: ${record.error || "Unknown error"}`
        };
        this.renderStatus(record.status, (_a = statusMessages[record.status]) != null ? _a : "Processing...");
        if (record.status === "completed") {
          this.renderOutput(record);
          return;
        }
        if (record.status === "failed") {
          throw new Error(record.error || "Generation failed");
        }
      } catch (err) {
        if (attempts >= maxAttempts)
          throw err;
      }
    }
    throw new Error("Generation timed out after 10 minutes.");
  }
  renderStatus(status, message) {
    var _a;
    this.statusSection.empty();
    const statusEl = this.statusSection.createDiv({ cls: "vidgen-status" });
    statusEl.setAttribute("data-status", status);
    const iconMap = {
      queued: "clock",
      dreaming: "sparkles",
      processing: "loader",
      completed: "check-circle",
      failed: "alert-circle"
    };
    const iconEl = statusEl.createDiv({ cls: "vidgen-status-icon" });
    (0, import_obsidian2.setIcon)(iconEl, (_a = iconMap[status]) != null ? _a : "loader");
    statusEl.createEl("span", { text: message, cls: "vidgen-status-text" });
    if (["queued", "dreaming", "processing"].includes(status)) {
      const progress = this.statusSection.createDiv({ cls: "vidgen-progress-bar" });
      progress.createDiv({ cls: "vidgen-progress-fill" });
    }
  }
  renderOutput(record) {
    this.outputSection.empty();
    this.outputSection.removeClass("vidgen-hidden");
    const outputCard = this.outputSection.createDiv({ cls: "vidgen-output-card" });
    if (record.videoUrl) {
      const videoWrapper = outputCard.createDiv({ cls: "vidgen-video-wrapper" });
      const video = videoWrapper.createEl("video", {
        cls: "vidgen-video",
        attr: {
          controls: "true",
          autoplay: "true",
          loop: "true",
          playsinline: "true"
        }
      });
      const source = video.createEl("source", {
        attr: { src: record.videoUrl, type: "video/mp4" }
      });
      video.appendChild(source);
    } else {
      outputCard.createEl("p", {
        text: "Video generated but URL not available.",
        cls: "vidgen-no-video"
      });
    }
    const outputMeta = outputCard.createDiv({ cls: "vidgen-output-meta" });
    outputMeta.createEl("p", { text: record.prompt, cls: "vidgen-output-prompt" });
    const outputActions = outputCard.createDiv({ cls: "vidgen-output-actions" });
    if (record.videoUrl) {
      const downloadBtn = outputActions.createEl("a", {
        cls: "vidgen-action-btn vidgen-download-btn",
        attr: { href: record.videoUrl, download: `vidgen-${record.id}.mp4`, target: "_blank" }
      });
      (0, import_obsidian2.setIcon)(downloadBtn, "download");
      downloadBtn.createSpan({ text: " Download" });
      const copyBtn = outputActions.createEl("button", {
        cls: "vidgen-action-btn"
      });
      (0, import_obsidian2.setIcon)(copyBtn, "copy");
      copyBtn.createSpan({ text: " Copy URL" });
      copyBtn.addEventListener("click", async () => {
        await navigator.clipboard.writeText(record.videoUrl);
        new import_obsidian2.Notice("Video URL copied to clipboard!");
      });
    }
  }
  renderHistory() {
    this.historySection.empty();
    if (this.history.length === 0)
      return;
    const histHeader = this.historySection.createDiv({ cls: "vidgen-history-header" });
    histHeader.createEl("h3", { text: "Recent Generations", cls: "vidgen-history-title" });
    const clearBtn = histHeader.createEl("button", {
      cls: "vidgen-clear-btn",
      title: "Clear history"
    });
    (0, import_obsidian2.setIcon)(clearBtn, "trash-2");
    clearBtn.addEventListener("click", async () => {
      this.history = [];
      await this.onSaveHistory(this.history);
      this.renderHistory();
    });
    const list = this.historySection.createDiv({ cls: "vidgen-history-list" });
    [...this.history].reverse().forEach((record) => {
      const item = list.createDiv({ cls: "vidgen-history-item" });
      item.setAttribute("data-status", record.status);
      const itemIcon = item.createDiv({ cls: "vidgen-history-icon" });
      if (record.status === "completed") {
        (0, import_obsidian2.setIcon)(itemIcon, "check-circle");
      } else if (record.status === "failed") {
        (0, import_obsidian2.setIcon)(itemIcon, "alert-circle");
      } else {
        (0, import_obsidian2.setIcon)(itemIcon, "loader");
      }
      const itemContent = item.createDiv({ cls: "vidgen-history-content" });
      itemContent.createEl("p", {
        text: record.prompt.length > 60 ? record.prompt.slice(0, 60) + "..." : record.prompt,
        cls: "vidgen-history-prompt"
      });
      const itemMeta = itemContent.createEl("span", { cls: "vidgen-history-meta" });
      const elapsed = record.completedAt ? `${Math.round((record.completedAt - record.createdAt) / 1e3)}s` : "";
      itemMeta.setText(
        `${record.provider === "luma" ? "Luma AI" : "Runway"} \xB7 ${record.aspectRatio} \xB7 ${record.duration}${elapsed ? " \xB7 " + elapsed : ""}`
      );
      const timestamp = new Date(record.createdAt).toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit"
      });
      itemContent.createEl("span", { text: timestamp, cls: "vidgen-history-time" });
      if (record.status === "completed" && record.videoUrl) {
        const playBtn = item.createEl("button", {
          cls: "vidgen-history-play",
          title: "View this video"
        });
        (0, import_obsidian2.setIcon)(playBtn, "play-circle");
        playBtn.addEventListener("click", () => {
          this.outputSection.empty();
          this.outputSection.removeClass("vidgen-hidden");
          this.renderOutput(record);
          this.outputSection.scrollIntoView({ behavior: "smooth" });
        });
      }
    });
  }
  addToHistory(record) {
    this.history.push(record);
    if (this.history.length > this.settings.historyLimit) {
      this.history.shift();
    }
    this.onSaveHistory(this.history);
    this.renderHistory();
  }
  getProvider() {
    if (this.settings.provider === "luma") {
      return new LumaProvider(this.settings.lumaApiKey);
    }
    return new RunwayProvider(this.settings.runwayApiKey);
  }
};
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// src/main.ts
var VidGenPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.history = [];
  }
  async onload() {
    await this.loadData();
    this.registerView(VIEW_TYPE_VIDGEN, (leaf) => {
      return new VideoGeneratorView(
        leaf,
        this.settings,
        this.history,
        async (h) => {
          this.history = h;
          await this.savePluginData();
        }
      );
    });
    this.addRibbonIcon("video", "Open VidGen", async () => {
      await this.activateView();
    });
    this.addCommand({
      id: "open-vidgen",
      name: "Open Video Generator",
      callback: async () => {
        await this.activateView();
      }
    });
    this.addSettingTab(new VidGenSettingsTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_VIDGEN);
  }
  async loadData() {
    var _a, _b;
    const raw = await super.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = raw == null ? void 0 : raw.settings) != null ? _a : {});
    this.history = (_b = raw == null ? void 0 : raw.history) != null ? _b : [];
  }
  async saveSettings() {
    await this.savePluginData();
    this.app.workspace.getLeavesOfType(VIEW_TYPE_VIDGEN).forEach((leaf) => {
      const view = leaf.view;
      if (view instanceof VideoGeneratorView) {
        view.updateSettings(this.settings);
      }
    });
  }
  async savePluginData() {
    const data = {
      settings: this.settings,
      history: this.history
    };
    await super.saveData(data);
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_VIDGEN);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    await leaf.setViewState({ type: VIEW_TYPE_VIDGEN, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
};
